---
- name: egov-apb provision
  hosts: localhost
  gather_facts: false
  connection: local
  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: ansibleplaybookbundle.asb-modules
  - role: provision-project
    playbook_debug: false
  vars:
    apb_action: provision
  vars_files:
    "/opt/apb/actions/vars/main.yml"
